#This script takes in a single protein report generated by protein_parsed_combiner.py and determine number of unique proteins identified.
#It outputs a file that shows the protein by accession and the number of times it was seen confidently.

'''
Usage: combined_protein_parsed_unique_checker.py protein_report_file
'''

import sys

report = sys.argv[1]

confident_proteins = 0
proteins_set = {}


with open(report,'r') as report_file:
	next(report_file)
	for line in report_file:
		line_split = line.strip().split('\t') #split tab delim line
		if not line_split[1] in proteins_set:
			proteins_set[line_split[1]] = 1
			confident_proteins += 1
		else:
			proteins_set[line_split[1]] += 1



print('%i Confident Proteins identified' % confident_proteins)

with open(report.split('.')[0] + '_unique_proteins.txt', 'w') as out_file:
	out_file.write('protein\tcount\n')
	for key in proteins_set:
		out_file.write('%s\t%i\n' % (key, proteins_set[key]))